import json
from datetime import datetime
import os

# 1. Load the scan results
if not os.path.exists('results.json'):
    print("❌ Error: results.json not found. Please run the semgrep scan first.")
    exit()

with open('results.json', 'r') as f:
    data = json.load(f)

findings = data.get('results', [])
total_issues = len(findings)

# Calculate unique files scanned
scanned_files = list(set(f['path'] for f in findings))
files_count = len(scanned_files) if len(scanned_files) > 0 else 1 

# 2. Define the HTML Template
html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Quantum-Shield Compliance Report</title>
    <style>
        body {{ font-family: 'Segoe UI', sans-serif; max-width: 800px; margin: 40px auto; color: #333; background-color: #f9f9f9; }}
        .header {{ background: #0f172a; color: #fff; padding: 30px; border-radius: 8px 8px 0 0; text-align: center; }}
        .summary {{ background: #fff; padding: 20px; border-bottom: 4px solid #3b82f6; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); }}
        .card {{ background: #fff; padding: 20px; margin-top: 20px; border-radius: 8px; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); border-left: 6px solid #ccc; }}
        .critical {{ border-left-color: #ef4444; }} /* Red */
        .warning {{ border-left-color: #eab308; }} /* Yellow */
        h1 {{ margin: 0; font-size: 2em; }}
        .tag {{ color: white; padding: 4px 8px; border-radius: 4px; font-size: 0.7em; font-weight: bold; vertical-align: middle; }}
        .tag-crit {{ background: #ef4444; }}
        .tag-warn {{ background: #eab308; color: black; }}
        code {{ background: #f1f5f9; padding: 2px 6px; border-radius: 4px; font-family: monospace; color: #d946ef; }}
        pre {{ background: #1e293b; color: #e2e8f0; padding: 15px; border-radius: 6px; overflow-x: auto; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🛡️ Quantum-Shield</h1>
        <p style="opacity: 0.8; margin-top: 5px;">Post-Quantum Cryptography Readiness Report</p>
    </div>
    
    <div class="summary">
        <h2 style="margin-top: 0;">Executive Summary</h2>
        <div style="display: flex; justify-content: space-between;">
            <div>
                <p><strong>Scan Date:</strong> {datetime.now().strftime("%Y-%m-%d %H:%M")}</p>
                <p><strong>Files Scanned:</strong> {files_count}</p>
            </div>
            <div style="text-align: right;">
                <p style="font-size: 1.2em;"><strong>Risk Score:</strong> <span style="color: #ef4444; font-weight: bold;">CRITICAL</span></p>
                <p>Issues Found: {total_issues}</p>
            </div>
        </div>
    </div>

    <h3>Detailed Findings</h3>
"""

# 3. Loop through findings and add to HTML
for issue in findings:
    rule_id = issue['check_id']
    message = issue['extra']['message']
    path = issue['path']
    line = issue['start']['line']
    code_snippet = issue['extra']['lines']

    # IMPROVED LOGIC: 
    # If it's AES or BouncyCastle -> Warning (Yellow). 
    # Everything else (RSA, OpenSSL, Crypto) -> Critical (Red).
    id_lower = rule_id.lower()
    
    if "aes" in id_lower or "bouncycastle" in id_lower:
        severity_class = "warning"
        tag_html = '<span class="tag tag-warn">WARNING</span>'
    else:
        severity_class = "critical"
        tag_html = '<span class="tag tag-crit">CRITICAL</span>'
    
    html_content += f"""
    <div class="card {severity_class}">
        <h4 style="margin-top: 0;">🚨 {rule_id} {tag_html}</h4>
        <p><strong>File:</strong> {path} (Line {line})</p>
        <pre>{code_snippet.strip()}</pre>
        <p><strong>Remediation:</strong></p>
        <p style="white-space: pre-wrap; color: #475569;">{message}</p>
    </div>
    """

html_content += """
    <div style="margin-top: 40px; text-align: center; color: #94a3b8; font-size: 0.9em;">
        Generated by Quantum-Shield Engine v1.0
    </div>
</body>
</html>
"""

# 4. Save the Report
with open('report.html', 'w', encoding='utf-8') as f:
    f.write(html_content)

print(f"✅ Success! Report generated: report.html ({total_issues} findings)")